[package]
name = "p3"
version = "0.1.0"
edition = "2021"
authors = ["krozzzis"]

[profile.release]
strip = true
lto = true

[dependencies]
cosmic-text = "0.12"
rfd = "0.14.1"

[dependencies.tokio]
version = "1.39.1"
features = ["fs"]

[dependencies.iced]
git = "https://github.com/iced-rs/iced"
features = ["canvas", "debug", "lazy", "advanced", "svg", "tokio"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
features = ["context_menu", "icons"]
