[package]
name = "gui"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Nikita Shumov"]

[dependencies]
rfd = "0.14.1"
core = { path = "../core" }
plugin = { path = "../plugin" }
theming = { path = "../theming" }
widget = { path = "../widget" }

[dependencies.tokio]
version = "1.39.1"
features = ["fs", "io-util"]

[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
branch = "master"
features = ["lazy", "advanced", "svg", "tokio"]
