[package]
name = "core"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Nikita Shumov"]

[dependencies]
iced_core = { git = "https://github.com/iced-rs/iced.git", branch = "master", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]
iced = ["dep:iced_core"]
