[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = { version = "0.8.9", optional = true }
core = { path = "../core" }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:toml"]
