[info]
name = "light"
description = "Default light theme"


# Button
[button.active]
background = "#ffefff"
text = "#800000"

[button.hover]
background = "#808080"
text = "#000000"


# Tab
[tab.active]
background = "#ffefff"
text = "#800000"
radius = 4.0

[tab.hover]
background = "#808080"
text = "#000000"
radius = 4.0

[tab.selected]
background = "#ff0000"
text = "#000000"
radius = 4.0


# TabBar
[tab_bar]
background = "#804040"
padding = 8.0
spacing = 4.0


# ListItem
[list_item.active]
background = "#ffffff00"
text = "#800000"
radius = 4.0

[list_item.hover]
background = "#808080"
text = "#000000"
radius = 4.0

[list_item.selected]
background = "#ff0000"
text = "#000000"
radius = 4.0


# List
[list]
padding = 8.0
spacing = 4.0


# Editor
[editor]
background = "#ffffff"
text = "#000000"
cursor = "#cc4444"
selection = "#ee8888"


# Editor
[notification]
background = "#ffffff"
text = "#000000"
border_color = "#cecece"
border_width = 1
radius = 4
shadow_x = 2
shadow_y = 2
shadow_blur = 2


# Notification List
[notification_list]
padding = 8.0
spacing = 4.0
