[info]
name = "light"
description = "Default light theme"


# Button
[button.active]
background = "#ffefff"
text = "#800000"

[button.hover]
background = "#808080"
text = "#000000"


# Tab
[tab.active]
background = "#ffefff"
text = "#800000"
radius = 4.0

[tab.hover]
background = "#808080"
text = "#000000"
radius = 4.0

[tab.selected]
background = "#ff0000"
text = "#000000"
radius = 4.0


# TabBar
[tab_bar]
background = "#400000"
padding = 8.0
spacing = 4.0


# ListItem
[list_item.active]
background = "#ffefff"
text = "#800000"
radius = 4.0

[list_item.hover]
background = "#808080"
text = "#000000"
radius = 4.0

[list_item.selected]
background = "#ff0000"
text = "#000000"
radius = 4.0
