[info]
name = "light"
description = "Default light theme"


[generic]
background = "#ffffff"
background2 = "#eeeeee"
text = "#000000"


# Buttons
## Primary button
[primary_button.active]
background = "#8fffff"
text = "#000000"

[primary_button.hover]
background = "#8ccccc"
text = "#303030"

## Secondary button
[secondary_button.active]
background = "#cecece"
text = "#000000"

[secondary_button.hover]
background = "#808080"
text = "#303030"

## Text button
[text_button.active]
background = "#ffffff00"
text = "#000000"

[text_button.hover]
background = "#ffffff00"
text = "#808000"


# Tab
[tab.active]
background = "#ffefff"
text = "#800000"
radius = 4.0

[tab.hover]
background = "#808080"
text = "#000000"
radius = 4.0

[tab.selected]
background = "#ff0000"
text = "#000000"
radius = 4.0


# TabBar
[tab_bar]
background = "#804040"
padding = 8.0
spacing = 4.0


# ListItem
[list_item.active]
background = "#ffffff00"
text = "#800000"
radius = 4.0

[list_item.hover]
background = "#808080"
text = "#000000"
radius = 4.0

[list_item.selected]
background = "#ff0000"
text = "#000000"
radius = 4.0


# List
[list]
spacing = 4.0


# Editor
[editor]
background = "#ffffff"
text = "#000000"
cursor = "#cc4444"
selection = "#ee8888"


# Notification
[notification]
background = "#ffffff"
text = "#000000"
border_color = "#cecece"
border_width = 1
radius = 4
shadow_x = 2
shadow_y = 2
shadow_blur = 2


# Notification List
[notification_list]
padding = 8.0
spacing = 4.0


# Context menu
[context_menu]
background = "#ffffff"
border_color = "#cecece"
border_width = 1
radius = 4
padding = 2
shadow_x = 2
shadow_y = 2
shadow_blur = 2


# File explorer
[file_explorer]
background = "#eeeeee"
text = "#000000"
padding = 4
width = 300
